// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqneulowxvxxidjkorma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxbmV1bG93eHZ4eGlkamtvcm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTM0NDYsImV4cCI6MjA2NTY2OTQ0Nn0.lDOtiTOR45AlPEFdA_7Vpw3Is8u-kcnlg2mVbbI1MzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);